version: "3.7"
services:
  auth-service:
    build: ./authService
    ports:
      - "4000:4000"

  notification-service:
    build: ./notificationService
    ports:
      - "4001:4001"

  real-time-service:
    build: ./real-time
    ports:
      - "5000:5000"

  client:
    build: ./notification-client
    ports:
      - "5173:5173"
