version: "3.7"
services:
  auth-service:
    build: ./auth-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
    ports:
      - "4000:4000"

  notification-service:
    build: ./notification-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/notifications
    ports:
      - "4001:4001"

  real-time-service:
    build: ./real-time-service
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
