version: "3.7"
services:
  auth-service:
    build: ./authService
    ports:
      - "4000:4000"

  notification-service:
    build: ./notificationService
    ports:
      - "4001:4001"

  real-time-service:
    build: ./real-time
    ports:
      - "3000:3000"

  client:
    build: ./notification-client
    ports:
      - "5173:5173"
    # depends_on:
    #   - auth-service
    #   - notification-service
    #   - real-time-service

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
# volumes:
#   mongo-data:
